### ISSUE TITLE
[FEATURE] Helper to make referenced object properties optional

### ISSUE THREAD

**Issue by Celleb** [johndcarmichael/boats#18]
Given a definition:

`post.yml`
```yaml
type: object
required:
  - name
  - coordinates
properties:
  name:
    type: string
  coordinates:
    type: array
    items:
      type: string
```
The helper should allow me to include it another definition with all the properties made optional.

i.e the result of using the helper will be something like this:

`patch.yml`
```yaml
type: object
properties:
  name:
    type: string
  coordinates:
    type: array
    items:
      type: string
```
