### ISSUE TITLE
model pick

### ISSUE THREAD

**Issue by johndcarmichael** [johndcarmichael/boats#32]
Openapi has a nice feature.. allOf.. but doesn't offer the ability to pick attributes from an existing model.

This allows you to create a set of base attributes to be used as say search results... lighter versions of the models. Then using allOf extend to create a fuller model for a detail view... but then when you need a 3rd version.. the whole thing becomes too complex to easily manage.

A function in boats to pick attribute from the full model to create a new model would be much easier to manage, all attributes held in the the main model, the lighters model cherry picking what they needed:
```
{{ pickForNewObject('../item/model.yml', ['name', 'description', 'createdAt']) }}
```
Would result in:
```
type: object
properties:
  description:
    type: string
  name:
    type: string
  createdAt
    type: string
    format: date-time
```

Where the full model might look like:
```
type: object
properties:
  comments:
    type: array
    items:
      $ref: ./comment/model.yml
  createdAt
    type: string
    format: date-time
  updatedAt
    type: string
    format: date-time
  deletedAt:
    type: string
    format: date-time
  description:
    type: string
  name:
    type: string
  likes:
    type: array
    items:
      $ref: ./like/model.yml
```

There will however be an issue when a picked attribute contains a $ref
